name: "7za Build"
on: 
  push:
    branches:
      - main 
  pull_request:
    branches: 
      - '*'
  workflow_dispatch:
jobs:
  macOS:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: 7za_2408_macOS
          path: /Users/runner/work/build-7Zip/build-7Zip/7z2408-src/CPP/7zip/Bundles/Alone/b
